name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to test environment
        run: |
          echo "Deploying to test environment"
          # Add your deployment commands here
